codecov:
  require_ci_to_pass: yes
  coverage:
    precision: 3
    round: up
    range: 0..100
    status:
      project:
        default:
          target: auto
          threshold: 2%
          base: auto
        java:
          target: 65%
          threshold: 1.5%
          base: auto
  parsers:
    java:
      detect_packages: true
      detect_classes: true
      detect_methods: true
      detect_annotations: true
      detect_constructors: true
      detect_fields: true
      author:
        enabled: yes
        email: yes
  comment:
    layout: "reach,diff,flags,files"
    behavior: default
    require_changes: no
    branches: null
    bot: codecov-io
    template:
      reporting: "On branch `{branch}` with commit `{commit}`\n\n{header}\n{files}\n{flags}\n\nCoverage Report:\n{coverage}"
    mode: "replace"
    require_changes: no
  flags:
    author:
      paths: "*"
      report: readme.md
      precision: 0
      fail_if_empty: yes
      fail_ci_if_empty: no
      threshold: null
      base: null
      name: "Authors"
    commits:
      paths: "*"
      report: readme.md
      precision: 0
      fail_if_empty: yes
      fail_ci_if_empty: no
      threshold: null
      base: null
      name: "Commits"
    errors:
      paths: "*"
      report: readme.md
      precision: 0
      fail_if_empty: yes
      fail_ci_if_empty: no
      threshold: null
      base: null
      name: "Errors"
    coverage:
      paths: "*"
      report: readme.md
      precision: 2
      fail_if_empty: yes
      fail_ci_if_empty: no
      threshold: 70
      base: null
      name: "Coverage"
    failures:
      paths: "*"
      report: readme.md
      precision: 0
      fail_if_empty: yes
      fail_ci_if_empty: no
      threshold: null
      base: null
      name: "Failures"
    time:
      paths: "*"
      report: readme.md
      precision: 0
      fail_if_empty: yes
      fail_ci_if_empty: no
      threshold: null
      base: null
      name: "Time"
