# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: Java CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        java-version: '1.8'
    - name: Build with Ant
      run: ant -noinput -buildfile build.xml
    - name: Test with Ant
      run: ant -buildfile build.xml test
      uses: codecov/codecov-action@v3
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
